<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QRS5SOS" failures="1" tests="3" name="Command line test" time="24.882" errors="0" timestamp="2023-01-23T17:47:51 IST">
  <testcase classname="frameWorkPackages.Test.ErrorValidationTest" name="LoginErrorValidation" time="1.142">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Username password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Username password do not match any user in this service]
at frameWorkPackages.Test.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="frameWorkPackages.Test.SubmitOrderTest" name="submitOrder" time="4.501"/>
  <testcase classname="frameWorkPackages.Test.SubmitOrderTest" name="submitOrder" time="2.301"/>
</testsuite> <!-- Command line test -->
