<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QRS5SOS" failures="1" tests="1" name="Error Validation Test" time="6.119" errors="0" timestamp="2023-01-23T17:56:10 IST">
  <testcase classname="frameWorkPackages.Test.ErrorValidationTest" name="LoginErrorValidation" time="1.384">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Username password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Username password do not match any user in this service]
at frameWorkPackages.Test.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
</testsuite> <!-- Error Validation Test -->
